### PR TITLE
Improve spanish translation

### PR DESCRIPTION
**Pull request by lekum**
A couple of typos, some improvements, including starting exclamation marks (¡) and capital letters for entities of the application (like `Flecha`, `Serie`, ...).

### CODE REVIEW

**Comment by lekum** [comment]
Please take on account that some of my corrections reflect the Castilian Spanish variant, and not the different latin-american variations. For example, `Entreno` may be correct, but since I saw it mixed with `Entrenamiento`, I opted for unifying them. Maybe an option could be to allow for different internationalization variants for Spanish.

**Comment by DreierF** [comment]
Hi,

Thanks for your pull request. Unfortunately I won't be able to merge it. The translation files are auto generated and will be overridden when the app compiles.
Please adjust the translation on the translation portal Crowdin (https://crowdin.com/project/mytargets).
All the changes you make there will automatically make it into the next app version.

**Comment by lekum** [comment]
Hi,

Thank you very much for your answer. I have visited Crowdin, and it seems (at least for your project) that I cannot translate to a variation of spanish (e.g. `es-ES`, *Castilian Spanish*) but only to a *generic* Spanish. Do you know if you could somehow configure it?

In case that you cannot specify it, if you want I could contribute to the translation, but take on account that it would be `es-ES` (and in the current translation I have seen that there are expressions mixed between `es-ES` and possibly `es-AR`).

Thanks,

**Comment by DreierF** [comment]
Hi,

I have just enabled Spanish, Argentina for you!
FYI: All strings that are not translated in Argentina are automatically copied from the Spanish translations. So if there are any general translation mistakes (that apply to all Spanish dialects) please fix them in the "Spanish" version.

Thanks in advance 🙂

**Comment by lekum** [comment]
Hi,

My idea was to contribute to the `es-ES` translation, so that the Argentinian one could be managed by their *mother tongue* speakers. I have done my contribution to the Spanish version. So now I can close the PR :-)

Thanks,

**Pull request closed without merging**
